name: Jest Tests
on: [push]
jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
         node-version: '16.14.2'
    - run: npm install
    - run: npm test