name: Jest Tests
on: [push]
jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2
    - name: Installing node
    - uses: actions/setup-node@v2
      with:
         node-version: '16.14.2'
    - name: Installing dependencies
    - run: npm install
    - name: Run tests
    - run: npm test